### ISSUE TITLE
Could not use in PhysicsEditor 1.8.4

### ISSUE THREAD

**Issue by explooosion** [eXponenta/pixi-poly#1]
Thank you for sharing.

I encountered some difficulties.

---

PhysicsEditor: 1.8.4 (2019-09-23)
macOS: Mojave 10.14.6 
---

Here is my `Explorers`:
![image](https://user-images.githubusercontent.com/13682994/75779223-32614580-5d94-11ea-876e-1ee4c6051d16.png)

When I save and restart, I got the error `Failed to load exporters...`
![image](https://user-images.githubusercontent.com/13682994/75779250-4147f800-5d94-11ea-84f7-384a66958faf.png)

I have try to copy `exporter.xml` and `pixi-poly.json` into `grantlee` and `pixi-poly-importer`.
And then seems to succeed.
![image](https://user-images.githubusercontent.com/13682994/75779465-984dcd00-5d94-11ea-9bb1-8d527a6cdd9c.png)

When I try to Publish, it still error `Failed to write...`
![image](https://user-images.githubusercontent.com/13682994/75779529-c03d3080-5d94-11ea-8459-47fd59f89456.png)

I'm not sure if my pixi-poly installer is correct.
Hope you can help me, thank you!

**Comment by explooosion** [comment]
Oh I'm so stupid!
I have found the problem and solved it, thank you.

**Comment by outrunthewolf** [comment]
What was the problem? I am also so stupid.

**Comment by outrunthewolf** [comment]
OK... I didnt follow the instructions properly. I think PhysicsEditor loops through folders in the folder location, so the root level folder should be just a holder rather than the actual custom exporter. duh..
